.PHONY: clean All

All:
	@echo "----------Building project:[ CalcMec - Release ]----------"
	@cd "CalcMec" && "$(MAKE)" -f  "CalcMec.mk"
clean:
	@echo "----------Cleaning project:[ CalcMec - Release ]----------"
	@cd "CalcMec" && "$(MAKE)" -f  "CalcMec.mk" clean
